apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  namespace: color-ns
spec:
  selector:
    matchLabels:
      app: green
  replicas: 5
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: subfuzion/colorteller:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: COLOR
            value: '<html style="background-color: green;"></html>'
          - name: SERVER_PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  namespace: color-ns
  name: green
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: green
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: color-ns
  name: green
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: green
    alb.ingress.kubernetes.io/group.order: '1'
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: green
              servicePort: 80
